name = "example_todo"
version = "1.0.0"
description = "Example Todo App using Instructed CQRS/ES framework"
target = "erlang"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"
gleam_otp = ">= 1.2.0 and < 2.0.0"
gleam_json = ">= 3.1.0 and < 4.0.0"
gleam_time = ">= 1.7.0 and < 2.0.0"
argv = ">= 1.0.2 and < 2.0.0"
youid = ">= 1.5.1 and < 2.0.0"
pog = ">= 4.1.0 and < 5.0.0"
instructed = { path = "../instructed" }
instructed_postgres = { path = "../instructed_postgres" }

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
