name = "example_todo_client"
version = "1.0.0"
description = "Todo CLI - lightweight Deno-based client"
target = "javascript"

[javascript]
runtime = "deno"

[javascript.deno]
allow_net = true
allow_read = true

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_fetch = ">= 1.0.0 and < 2.0.0"
gleam_http = ">= 4.3.0 and < 5.0.0"
gleam_javascript = ">= 0.15.0 and < 2.0.0"
gleam_json = ">= 3.1.0 and < 4.0.0"
argv = ">= 1.0.2 and < 2.0.0"
youid = ">= 1.5.1 and < 2.0.0"
todo_shared = { path = "../shared" }

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
